---
- name: Ambari Repo
  yum_repository:
    name: ambari-2.4.4
    description: "Ambari Repo"
    baseurl: "{{ ambari_repo }}"
    failovermethod: priority
    gpgkey: "http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.2.0/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"
    gpgcheck: yes
    enabled: yes
